### ISSUE TITLE
Bug on line 815

### ISSUE THREAD

**Issue by thailehuy** [bountysource/scope.js#3]
loop `j` but increase `i`

``` javascript
// page not found
for (j=0; j < scope.routes.length; i++) {
```

**Comment by wkonkel** [comment]
I just pushed a bunch of commits for 0.5.1 which fixes this issue among many others.  It's great you're using scope.js but it's fairly unstable right now and will change a lot over next few weeks.  I'm hoping to launch an 0.6.0 afterwards which will be far more stable.   Any suggestions?
